### ISSUE TITLE
Request-A-Team app NOT working

### ISSUE THREAD

**Issue by MandyS83** [OfficeDev/microsoft-teams-apps-requestateam#341]
Installed App successfully, 
when try to access getting this error message 
![image](https://user-images.githubusercontent.com/98364851/151099635-b449fed7-cd57-4ff4-8f58-94e3d29ae7ef.png)

Can you please assist?

**Comment by sneranacdw** [comment]
We are getting exact same error after successfully Installation and configuration. Not sure where it is disconnecting.

**Comment by sneranacdw** [comment]
Quick update: This error suddenly disappeared now. Though, we don't see any teams nor associated site getting provisioned

**Comment by MandyS83** [comment]
Hi Team, I have tested and still getting same error message, Please investigate and assist with resolving this error

![image](https://user-images.githubusercontent.com/98364851/152070594-4edba1ef-6bc0-4f97-85a1-39ee1b4f094d.png)

**Comment by sneranacdw** [comment]
I am getting list not found in logic App workflow

**Comment by sneranacdw** [comment]
Update:
I was able to resolve this error. The solution was to remove the List GUID instead of the List name in the Logic App. After that it provisioned both Sharepoint site and the Team

**Comment by sneranacdw** [comment]
I deployed this App in Production and am getting following error:

![image](https://user-images.githubusercontent.com/67337246/152538575-2aab3653-50e3-4b52-93d4-508b90e6aaba.png)

**Comment by SammiRasha** [comment]
Hi, I faced this error a little while ago. Trying to rack my brain on how I fixed it -- can you check your connectors in your powerapp please? I don't have it installed currently to provide a custom screenshot, but do this step of the deployment guide again. For me even though I did this step and it showed that it connected to my sharepoint site in the data sources view on the left, when I hovered over them I saw it was still connected to the template website from the owner. Re-add them and see if that works. Will try to think of the other fixes I did as well which may have been related to it
![image](https://user-images.githubusercontent.com/10238857/152889240-00b6d554-a3ea-429f-aa9e-3a2741063869.png)

**Comment by sneranacdw** [comment]
I was able to fix this error. You will need to make sure to add correct Group ID as per the deployment guide. Save and Publish this change. Unless you perform the last step your new Group ID won't take effect

**Comment by alexc-MSFT** [comment]
As others have said above, you need to edit the OnStart event of the app object and update the ID in that code with an ID of a group in your tenant where your admin users will reside.

We are planning on making some improvements to the documentation to make this process easier to understand.

@SammiRasha FYI

**Comment by theyssef** [comment]
Hello All,
I updated the GroupID in the Onstart event and saved it:
![image](https://user-images.githubusercontent.com/39700794/156142356-6ef9e213-d266-4463-acac-590de9647f34.png)

However, when I launch the app I still get the error where it is pointing to the wrong GroupID, what could be causing this?
![image](https://user-images.githubusercontent.com/39700794/156142630-c74c6eb8-c08d-44f0-8c08-787169fe6c91.png)

**Comment by NoMan0013** [comment]
@theyssef did you republish the app?

**Comment by theyssef** [comment]
> @theyssef did you republish the app?

Hi Noman0013,
Thanks for the hint, that was indeed it.

I published the app using the following guidance: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/save-publish-app ; and now the error is gone

**Comment by 7gizmo** [comment]
I had the same error, did you import and configure the power app with the service user? If not delete PowerApps and Flows and go through the instructions with the service user in the PowerApp and Flow section.
